### ISSUE TITLE
Overview of current features of language server

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/language-tools#83]
This is an overview of the current state of the `svelte-language-server` - what it already can do, what it cannot, yet. If you feel a feature is missing or something that should work according to this list does not work, open a new issue.

#### autocompletion / auto imports
- [x] autocompletion for normal html tags
- [x] autocompletion for special svelte tags like `<svelte:window>`
- [x] autocompletion for special svelte tags like `#await`

#### hover info
- [x] hover info for normal html tags
- [x] hover info for special svelte tags like `<svelte:window>`
- [x] hover info for special svelte tags like `#await`

## CSS

- [x] support for CSS/Less/SCSS

#### autocompletion / auto imports
- [x] autocompletion for css tags
- [x] autocompletion for `:global` tag

#### hover info
- [x] hover info for css tags

#### go to definition
- [ ] go to definition from class in template to css
- [ ] go to definition from css to template

## Javascript / Typescript

- [ ] semantic highlighting (#71)
- [x] show svelte parser/compiler warnings/errors
- [ ] typescript-support for $-syntax (`$: ...` and `$variableSubcribeShortHand`) (#57)

#### go to definition
- [x] go to definition within script
- [x] go to definition to non-svelte file
- [ ] go to definition from template to script (#57)
- [ ] go to definition from component-tag to component (#57)
- [ ] go to definition from component-property in template to component (#57)

#### typechecking
- [x] typechecking capabilities for script
- [ ] typechecking capabilities for component props (#57)
- [ ] typechecking capabilities for component events
- [x] support for `//@ts-check` / `//@ts-nocheck`
- [x] JSDoc support

#### autocompletion / auto imports
- [x] autocompletion/autoimport inside script
- [ ] autocomplete/autoimport of svelte component inside template (#57)
- [ ] autocomplete of svelte component props (#57)
- [ ] autocomplete of svelte component events

#### code actions
- [ ] organize imports support (#72)
- [ ] rename function/variable
- [ ] rename svelte component default import
- [ ] rename svelte component prop
